import test from 'node:test';import assert from 'node:assert/strict';import ganache from 'ganache';
import {BrowserProvider,ContractFactory,parseUnits,keccak256,toUtf8Bytes} from 'ethers';import {compile} from '../scripts/compile.mjs';
test('holds USDC, releases milestones, freezes disputes, and returns future funds',async t=>{
 const engine=ganache.provider({logging:{quiet:true},chain:{chainId:1337,hardfork:'shanghai'},wallet:{totalAccounts:6}});const provider=new BrowserProvider(engine);t.after(async()=>{provider.destroy();await engine.disconnect()});
 const [client,worker,arbiter,outsider]=await Promise.all([0,1,2,3].map(i=>provider.getSigner(i)));const {ScopePay,MockUSDC}=compile();
 const token=await new ContractFactory(MockUSDC.abi,MockUSDC.bytecode,client).deploy();await token.waitForDeployment();const escrow=await new ContractFactory(ScopePay.abi,ScopePay.bytecode,client).deploy(await token.getAddress());await escrow.waitForDeployment();
 const funded=parseUnits('6200',6);await(await token.mint(await client.getAddress(),funded)).wait();await(await token.approve(await escrow.getAddress(),funded)).wait();const now=Math.floor(Date.now()/1000);const terms=keccak256(toUtf8Bytes('signed-scope-v1'));
 await(await escrow.createDeal(await worker.getAddress(),await arbiter.getAddress(),[parseUnits('1200',6),parseUnits('1800',6),parseUnits('3200',6)],[now+3600,now+7200,now+10800],terms)).wait();assert.equal(await token.balanceOf(await escrow.getAddress()),funded);
 const evidence=keccak256(toUtf8Bytes('milestone-evidence'));await assert.rejects((async()=>(await escrow.connect(outsider).submitMilestone(0,0,evidence)).wait())());await(await escrow.connect(worker).submitMilestone(0,0,evidence)).wait();await assert.rejects((async()=>(await escrow.connect(worker).approveMilestone(0,0)).wait())());await(await escrow.connect(client).approveMilestone(0,0)).wait();assert.equal(await token.balanceOf(await worker.getAddress()),parseUnits('1200',6));
 await(await escrow.connect(worker).openDispute(0,keccak256(toUtf8Bytes('scope mismatch')))).wait();await assert.rejects((async()=>(await escrow.connect(client).approveMilestone(0,1)).wait())());await assert.rejects((async()=>(await escrow.connect(outsider).resolveDispute(0,parseUnits('500',6))).wait())());await(await escrow.connect(arbiter).resolveDispute(0,parseUnits('500',6))).wait();
 assert.equal(await token.balanceOf(await worker.getAddress()),parseUnits('1700',6));assert.equal(await token.balanceOf(await client.getAddress()),parseUnits('4500',6));assert.equal((await escrow.deals(0)).closed,true);assert.equal(await token.balanceOf(await escrow.getAddress()),0n);
});
